[tools]
go = "1.24.2"
golangci-lint = "2.1.5"
hadolint = "2.12.0"
node = "23.11.0"
pre-commit = "4.2.0"

[tasks.bootstrap]
description = "Sets up the development environment"
run = [
	"mise install",
	"pre-commit install --install-hooks",
	"pre-commit run --all-files",
]
