---
name: Continuous Integration

on:
  pull_request:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: pre-commit
        shell: bash
        run: pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Tests
        shell: bash
        run: gotestsum --format=github-actions -- ./... -race

      - uses: docker/setup-buildx-action@v3

      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          tags: durandj/ek:ci
          push: false

      - uses: goreleaser/goreleaser-action@v6
        with:
          version: latest
          args: check
