---
name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - name: pre-commit
        shell: bash
        run: pre-commit run --show-diff-on-failure --color=always --all-files
      - name: Tests
        shell: bash
        run: gotestsum --format=github-actions -- ./... -race

      # TODO: docker image
