---
name: Continuous Delivery

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: jdx/mise-action@v2

      - uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-3|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}

      - name: pre-commit
        shell: bash
        run: pre-commit run --show-diff-on-failure --color=always --all-files

      - name: Tests
        shell: bash
        run: gotestsum --format=github-actions -- ./... -race

      - uses: docker/setup-buildx-action@v3

      - name: Docker build
        uses: docker/build-push-action@v6
        with:
          tags: durandj/ek:ci
          push: false

  tag-release:
    runs-on: ubuntu-latest
    environment: release

    needs: test

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: go-semantic-release/action@v1
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
